repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: git@github.com:psf/black.git
    rev: 23.10.0
    hooks:
    -   id: black