repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
-   repo: local
    hooks:
    -   id: pytest
        name: Run pytest
        entry: python -m pytest
        language: system
        types: [python]
        pass_filenames: false
