name: c1_coursework_wp289
channels:
  - defaults
dependencies:
  - black=23.3.0
  - pre-commit
  - cython=3.0.0
  - pytest=7.4.0
  - pip=23.3
  - pip:
      - flake8==6.1.0
      - sphinx==7.2.6
      - pydata-sphinx-theme==0.14.3
