name: c1_coursework_wp289
channels:
  - defaults
dependencies:
  - python=3.12.0
  - black=23.3.0
  - cython=3.0.0
  - numpy=1.26.2
  - pre-commit
  - pytest=7.4.0
  - wheel=0.41.2
  - pip=23.3
  - pip:
      - flake8==6.1.0
      - sphinx==7.2.6
      - pydata-sphinx-theme==0.14.3
      - pygments==2.17.1
